version: '3'
services:
  express-acc:
    image: sessionstechnology/expressacc:latest
    environment:
      - TZ=America/New_York
    # build:
    #   dockerfile: Dockerfile
    #   context: .
    ports:
      - '3001:3001'
    volumes:
      - express-acc:/lowdb
    restart: unless-stopped

volumes:
  express-acc:
