import '@mdi/font/css/materialdesignicons.css'
import 'vuetify/styles'
import { createVuetify } from 'vuetify'

export default createVuetify({
  theme: {
    defaultTheme: 'routioneer',
    themes: {
      routioneer: {
        dark: false,
        colors: {
          background: '#F4F7FB',
          surface: '#FFFFFF',
          'surface-variant': '#F0F3F9',
          'on-background': '#182238',
          'on-surface': '#182238',
          'on-surface-variant': '#667289',
          primary: '#5269E8',
          'on-primary': '#FFFFFF',
          secondary: '#7861D8',
          'on-secondary': '#FFFFFF',
          accent: '#F27C68',
          'on-accent': '#38140C',
          error: '#D95763',
          'on-error': '#32090F',
          warning: '#D78D25',
          'on-warning': '#322105',
          success: '#319C75',
          'on-success': '#09271C',
          info: '#3B92C4',
          'on-info': '#092435',
        },
      },
      routioneerDark: {
        dark: true,
        colors: {
          background: '#111722',
          surface: '#192231',
          'surface-variant': '#202B3C',
          'on-background': '#F4F6FB',
          'on-surface': '#F4F6FB',
          'on-surface-variant': '#AAB4C5',
          primary: '#91A2FF',
          'on-primary': '#11182D',
          secondary: '#B19AF4',
          'on-secondary': '#1D1535',
          accent: '#FF9A86',
          'on-accent': '#38140C',
          error: '#FF8B94',
          'on-error': '#3A0D12',
          warning: '#F4BF69',
          'on-warning': '#322105',
          success: '#69D1AA',
          'on-success': '#09271C',
          info: '#76C4EF',
          'on-info': '#092435',
        },
      },
    },
  },
  defaults: {
    VBtn: { rounded: 'lg', elevation: 0 },
    VCard: { rounded: 'xl' },
    VAlert: { rounded: 'lg' },
    VChip: { rounded: 'lg' },
    VTextField: { variant: 'outlined', density: 'comfortable', color: 'primary', bgColor: 'surface' },
    VSelect: { variant: 'outlined', density: 'comfortable', color: 'primary', bgColor: 'surface' },
    VFileInput: { variant: 'outlined', density: 'comfortable', color: 'primary', bgColor: 'surface' },
    VListItem: { rounded: 'lg' },
  },
})
